@startuml
title Andorid Start Case
rnote over "Android UI Thread"
 Recieve this start command 
 from the button and send start
 Command to the 
 Send Inforamtion Thread.
endrnote
"Android UI Thread" -> "Send Inforamtion Thread" : Commando to start working.
rnote over "Send Inforamtion Thread"
 Start the two threas Bluetooth Thread
 and Position Thread. and recieve this 
 information and it sends to the wifi/tcp
 communication thread.
endrnote
"Send Inforamtion Thread" <- "Bluetooth Thread" : Magnet Interruption Count
"Send Inforamtion Thread" <- "Position Thread" : Relative position of the phone
rnote over "Android UI Thread"
 Send the position and the velocity to the 
 UI Thread.
endrnote
"Send Inforamtion Thread" -> "Android UI Thread" : Send data of Phone Position and Roller Velocity.
@enduml